// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2YbN6PiTcNUirV8cvs3MBA1ezGWgZqg',
    appId: '1:476513953802:web:dfa0a235159a0e5e9d57f3',
    messagingSenderId: '476513953802',
    projectId: 'chat-app-9ecd0',
    authDomain: 'chat-app-9ecd0.firebaseapp.com',
    storageBucket: 'chat-app-9ecd0.appspot.com',
    measurementId: 'G-5BWHT1QYLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHzSwgTPeOSae3oLkyFyDVDhjY2F1xANk',
    appId: '1:476513953802:android:21782eb04a17fa689d57f3',
    messagingSenderId: '476513953802',
    projectId: 'chat-app-9ecd0',
    storageBucket: 'chat-app-9ecd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIPkvT2C9D74e9chZkF2JkLDlyCm6db4',
    appId: '1:476513953802:ios:7c8cfd5d00bc9bfe9d57f3',
    messagingSenderId: '476513953802',
    projectId: 'chat-app-9ecd0',
    storageBucket: 'chat-app-9ecd0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIPkvT2C9D74e9chZkF2JkLDlyCm6db4',
    appId: '1:476513953802:ios:87a446e755acb2f59d57f3',
    messagingSenderId: '476513953802',
    projectId: 'chat-app-9ecd0',
    storageBucket: 'chat-app-9ecd0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
